sudo: false
language: node_js
node_js:
  - node
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
before_script:
  - webdriver-manager clean
  - webdriver-manager update --versions.chrome=73.0.3683
  - ls -l /home/travis/build/tom-weatherhead/thaw-angular-component-library/node_modules/protractor/node_modules/webdriver-manager/selenium
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run all-for-travis
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
